version: '3.1'

services:
  shorten_db:
    container_name: shorten_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: shorten
      POSTGRES_PASSWORD: shorten123
      POSTGRES_DB: shorten
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
volumes:
  shorten_db: